#!/usr/bin/env python

import sys
import subprocess

opre = subprocess.run([
	"curl", 
	f"https://api.github.com/users/{sys.argv[1]}/events"
], capture_output=True, text=True, check=True)
print(opre.stdout)
